--DROP VIEWS
DROP VIEW SCHEMA_TIENDA.VW_PRODUCTOS_VENDIDOS;
DROP VIEW SCHEMA_TIENDA.VW_VENTAS_MENSUALES;

CREATE VIEW SCHEMA_TIENDA.VW_PRODUCTOS_VENDIDOS (
    ID_PRODUCTO,
    NOMBRE_DEL_PRODUCTO,
    DESCRIPCION_DEL_PRODUCTO,
    PRECIO_DEL_PRODUCTO,
    STOCK_DISPONIBLE,
    ID_PROVEEDOR,
    NOMBRE_DEL_PROVEEDOR,
    ID_CATEGORIA,
    CATEGORIA,
    TOTAL_VENDIDO,
    UM
) AS
SELECT P.ID_PRODUCTO,
    P.NOMBRE AS NOMBRE_DEL_PRODUCTO,
    P.DESCRIPCION AS DESCRIPCION_DEL_PRODUCTO,
    P.PRECIO AS PRECIO_DEL_PRODUCTO,
    P.STOCK AS STOCK_DISPONIBLE,
    P.ID_PROVEEDOR,
    PR.NOMBRE AS NOMBRE_DEL_PROVEEDOR,
    P.ID_CATEGORIA,
    C.DESCRIPCION AS CATEGORIA,
    SUM(VP.CANTIDAD) AS TOTAL_VENDIDO,
    VP.UM
FROM SCHEMA_TIENDA.TBL_PRODUCTOS P
    JOIN SCHEMA_TIENDA.TBL_VENTAS_PRODUCTOS VP ON P.ID_PRODUCTO = VP.ID_PRODUCTO
    JOIN SCHEMA_TIENDA.TBL_PROVEEDORES PR ON P.ID_PROVEEDOR = PR.ID_PROVEEDOR
    JOIN SCHEMA_TIENDA.TBL_CATEGORIAS C ON P.ID_CATEGORIA = C.ID_CATEGORIA
GROUP BY P.ID_PRODUCTO,
    P.NOMBRE,
    P.DESCRIPCION,
    P.PRECIO,
    P.STOCK,
    P.ID_PROVEEDOR,
    PR.NOMBRE,
    P.ID_CATEGORIA,
    C.DESCRIPCION,
    VP.UM;

CREATE VIEW SCHEMA_TIENDA.VW_VENTAS_MENSUALES ( ANIO, MES, NUMERO_DE_VENTAS, TOTAL_VENTAS ) AS SELECT YEAR(FECHA) AS ANIO,
    MONTH(FECHA) AS MES,
    COUNT(ID_VENTA) AS NUMERO_DE_VENTAS,
    SUM(TOTAL) AS TOTAL_VENTAS
FROM SCHEMA_TIENDA.TBL_VENTAS
GROUP BY YEAR(FECHA), MONTH(FECHA);