/*DROP INDEX SCHEMA_TIENDA.IDX_CARGOS_DEPARTAMENTO;
DROP INDEX SCHEMA_TIENDA.IDX_CLIENTES_CODIGO_CLIENTE;
DROP INDEX SCHEMA_TIENDA.IDX_COLABORADORES_CODIGO_COLABORADOR;
DROP INDEX SCHEMA_TIENDA.IDX_CUENTAS_USUARIO;
DROP INDEX SCHEMA_TIENDA.IDX_MOVIMIENTOS_PRODUCTO;
DROP INDEX SCHEMA_TIENDA.IDX_PRODUCTOS_CATEGORIA;
DROP INDEX SCHEMA_TIENDA.IDX_PRODUCTOS_PROVEEDOR;
DROP INDEX SCHEMA_TIENDA.IDX_UNIQUE_CUENTA;
DROP INDEX SCHEMA_TIENDA.IDX_UNIQUE_DNI;
DROP INDEX SCHEMA_TIENDA.IDX_VENTAS_CLIENTE;
DROP INDEX SCHEMA_TIENDA.IDX_VENTAS_COLABORADOR;
DROP INDEX SCHEMA_TIENDA.IDX_VENTAS_PRODUCTOS_PRODUCTO;
DROP INDEX SCHEMA_TIENDA.IDX_VENTAS_PRODUCTOS_VENTA;
*/

CREATE UNIQUE INDEX SCHEMA_TIENDA.idx_unique_dni ON SCHEMA_TIENDA.TBL_USUARIOS(DNI);
CREATE UNIQUE INDEX SCHEMA_TIENDA.idx_unique_cuenta on SCHEMA_TIENDA.TBL_CUENTAS(cuenta);
CREATE INDEX SCHEMA_TIENDA.idx_cuentas_usuario ON SCHEMA_TIENDA.TBL_CUENTAS(ID_USUARIO);
CREATE INDEX SCHEMA_TIENDA.idx_cargos_departamento ON SCHEMA_TIENDA.TBL_CARGOS(ID_DEPARTAMENTO);
CREATE INDEX SCHEMA_TIENDA.idx_productos_categoria ON SCHEMA_TIENDA.TBL_PRODUCTOS(ID_CATEGORIA);
CREATE INDEX SCHEMA_TIENDA.idx_productos_proveedor ON SCHEMA_TIENDA.TBL_PRODUCTOS(ID_PROVEEDOR);
CREATE INDEX SCHEMA_TIENDA.idx_movimientos_producto ON SCHEMA_TIENDA.TBL_MOVIMIENTOS_MERCADERIA(ID_PRODUCTO);
CREATE INDEX SCHEMA_TIENDA.idx_ventas_cliente ON SCHEMA_TIENDA.TBL_VENTAS(ID_CLIENTE);
CREATE INDEX SCHEMA_TIENDA.idx_ventas_colaborador ON SCHEMA_TIENDA.TBL_VENTAS(ID_COLABORADOR);
CREATE INDEX SCHEMA_TIENDA.idx_ventas_productos_producto ON SCHEMA_TIENDA.TBL_VENTAS_PRODUCTOS(ID_PRODUCTO);
CREATE INDEX SCHEMA_TIENDA.idx_ventas_productos_venta ON SCHEMA_TIENDA.TBL_VENTAS_PRODUCTOS(ID_VENTA);
CREATE INDEX SCHEMA_TIENDA.idx_clientes_codigo_cliente ON SCHEMA_TIENDA.TBL_CLIENTES(CODIGO_CLIENTE);
CREATE INDEX SCHEMA_TIENDA.idx_colaboradores_codigo_colaborador ON SCHEMA_TIENDA.TBL_COLABORADORES(CODIGO_COLABORADOR);