--DELETE FROM SCHEMA_TIENDA.TBL_CATEGORIAS;

INSERT INTO SCHEMA_TIENDA.TBL_CATEGORIAS (DESCRIPCION) VALUES ('Electrónica');
INSERT INTO SCHEMA_TIENDA.TBL_CATEGORIAS (DESCRIPCION) VALUES ('Ropa');
INSERT INTO SCHEMA_TIENDA.TBL_CATEGORIAS (DESCRIPCION) VALUES ('Muebles');
INSERT INTO SCHEMA_TIENDA.TBL_CATEGORIAS (DESCRIPCION) VALUES ('Juguetes');
INSERT INTO SCHEMA_TIENDA.TBL_CATEGORIAS (DESCRIPCION) VALUES ('Hogar');
INSERT INTO SCHEMA_TIENDA.TBL_CATEGORIAS (DESCRIPCION) VALUES ('Deportes');
INSERT INTO SCHEMA_TIENDA.TBL_CATEGORIAS (DESCRIPCION) VALUES ('Belleza');
INSERT INTO SCHEMA_TIENDA.TBL_CATEGORIAS (DESCRIPCION) VALUES ('Libros');
INSERT INTO SCHEMA_TIENDA.TBL_CATEGORIAS (DESCRIPCION) VALUES ('Alimentos');
INSERT INTO SCHEMA_TIENDA.TBL_CATEGORIAS (DESCRIPCION) VALUES ('Automotriz');
INSERT INTO SCHEMA_TIENDA.TBL_CATEGORIAS (DESCRIPCION) VALUES ('Música');
INSERT INTO SCHEMA_TIENDA.TBL_CATEGORIAS (DESCRIPCION) VALUES ('Electrodomésticos');
INSERT INTO SCHEMA_TIENDA.TBL_CATEGORIAS (DESCRIPCION) VALUES ('Joyería');
INSERT INTO SCHEMA_TIENDA.TBL_CATEGORIAS (DESCRIPCION) VALUES ('Arte');
INSERT INTO SCHEMA_TIENDA.TBL_CATEGORIAS (DESCRIPCION) VALUES ('Herramientas');


--DELETE FROM SCHEMA_TIENDA.TBL_TURNOS;
INSERT INTO SCHEMA_TIENDA.TBL_TURNOS (DESCRIPCION, HORA_INICIO, HORA_FIN)
VALUES ('Turno completo', '08:00:00', '16:00:00');
INSERT INTO SCHEMA_TIENDA.TBL_TURNOS (DESCRIPCION, HORA_INICIO, HORA_FIN)
VALUES ('Part time - Mañana', '08:00:00', '12:00:00');
INSERT INTO SCHEMA_TIENDA.TBL_TURNOS (DESCRIPCION, HORA_INICIO, HORA_FIN)
VALUES ('Part time - Tarde', '12:00:00', '16:00:00');