--Código por si se necesita reestablecer el valor autogenerado del PK
--ALTER TABLE SCHEMA_TIENDA.TBL_TU_TABLA ALTER COLUMN TU_COLUMNA RESTART WITH 1;


--DELETE FROM SCHEMA_TIENDA.TBL_CATEGORIAS;

INSERT INTO SCHEMA_TIENDA.TBL_CATEGORIAS (DESCRIPCION) VALUES ('Electrónica');
INSERT INTO SCHEMA_TIENDA.TBL_CATEGORIAS (DESCRIPCION) VALUES ('Ropa');
INSERT INTO SCHEMA_TIENDA.TBL_CATEGORIAS (DESCRIPCION) VALUES ('Muebles');
INSERT INTO SCHEMA_TIENDA.TBL_CATEGORIAS (DESCRIPCION) VALUES ('Juguetes');
INSERT INTO SCHEMA_TIENDA.TBL_CATEGORIAS (DESCRIPCION) VALUES ('Hogar');
INSERT INTO SCHEMA_TIENDA.TBL_CATEGORIAS (DESCRIPCION) VALUES ('Deportes');
INSERT INTO SCHEMA_TIENDA.TBL_CATEGORIAS (DESCRIPCION) VALUES ('Belleza');
INSERT INTO SCHEMA_TIENDA.TBL_CATEGORIAS (DESCRIPCION) VALUES ('Libros');
INSERT INTO SCHEMA_TIENDA.TBL_CATEGORIAS (DESCRIPCION) VALUES ('Alimentos');
INSERT INTO SCHEMA_TIENDA.TBL_CATEGORIAS (DESCRIPCION) VALUES ('Automotriz');
INSERT INTO SCHEMA_TIENDA.TBL_CATEGORIAS (DESCRIPCION) VALUES ('Música');
INSERT INTO SCHEMA_TIENDA.TBL_CATEGORIAS (DESCRIPCION) VALUES ('Electrodomésticos');
INSERT INTO SCHEMA_TIENDA.TBL_CATEGORIAS (DESCRIPCION) VALUES ('Joyería');
INSERT INTO SCHEMA_TIENDA.TBL_CATEGORIAS (DESCRIPCION) VALUES ('Arte');
INSERT INTO SCHEMA_TIENDA.TBL_CATEGORIAS (DESCRIPCION) VALUES ('Herramientas');


--DELETE FROM SCHEMA_TIENDA.TBL_TURNOS;
INSERT INTO SCHEMA_TIENDA.TBL_TURNOS (DESCRIPCION, HORA_INICIO, HORA_FIN)
VALUES ('Turno completo', '08:00:00', '16:00:00');
INSERT INTO SCHEMA_TIENDA.TBL_TURNOS (DESCRIPCION, HORA_INICIO, HORA_FIN)
VALUES ('Part time - Mañana', '08:00:00', '12:00:00');
INSERT INTO SCHEMA_TIENDA.TBL_TURNOS (DESCRIPCION, HORA_INICIO, HORA_FIN)
VALUES ('Part time - Tarde', '12:00:00', '16:00:00');

--DELETE FROM SCHEMA_TIENDA.TBL_DEPARTAMENTOS;
INSERT INTO SCHEMA_TIENDA.TBL_DEPARTAMENTOS (DESCRIPCION)
VALUES ('Ventas'),
       ('Almacén'),
       ('Marketing'),
       ('Recursos Humanos'),
       ('Seguridad'),
       ('Limpieza');

--DELETE FROM SCHEMA_TIENDA.TBL_CARGOS;
INSERT INTO SCHEMA_TIENDA.TBL_CARGOS (DESCRIPCION, REMUNERACION, ID_DEPARTAMENTO)
VALUES ('Gerente de Ventas', 5000.00, 1),
       ('Asistente de Ventas', 3000.00, 1),
       ('Jefe de Almacén', 4500.00, 2),
       ('Auxiliar de Almacén', 2500.00, 2),
       ('Jefe de Marketing', 4800.00, 3),
       ('Auxiliar de RRHH', 4200.00, 4),
       ('Guardia de Seguridad', 3500.00, 5),
       ('Personal de Limpieza', 2300.00, 6);

--DELETE FROM SCHEMA_TIENDA.TBL_USUARIOS;
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Diego', 'De la Cruz', 'Torres', 'Diego De la Cruz Torres', '72217227', 'M', 987060404, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Hugo', 'Quispe', 'Fernández', 'Hugo Quispe Fernández', '72697641', 'M', 955278920, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Mateo', 'Flores', 'Vargas', 'Mateo Flores Vargas', '70952293', 'M', 990415092, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Martín', 'Sánchez', 'Gutiérrez', 'Martín Sánchez Gutiérrez', '73828403', 'M', 982599992, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Lucas', 'García', 'Cruz', 'Lucas García Cruz', '71208660', 'M', 996138193, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Leo', 'Rodríguez', 'Ruiz', 'Leo Rodríguez Ruiz', '70368518', 'M', 997911287, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Daniel', 'Huamán', 'De la Cruz', 'Daniel Huamán De la Cruz', '71255740', 'M', 973489183, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Alejandro', 'Rojas', 'Romero', 'Alejandro Rojas Romero', '72556703', 'M', 982730306, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Manuel', 'Vásquez', 'Gómez', 'Manuel Vásquez Gómez', '72875631', 'M', 997698316, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Pablo', 'Mamani', 'Silva', 'Pablo Mamani Silva', '70815054', 'M', 958673449, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Álvaro', 'López', 'Córdova', 'Álvaro López Córdova', '71049734', 'M', 979672668, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Adrián', 'Ramos', 'Condori', 'Adrián Ramos Condori', '72933778', 'M', 974822880, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Enzo', 'Pérez', 'Catro', 'Enzo Pérez Catro', '70877779', 'M', 965512544, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Mario', 'Torres', 'Martínez', 'Mario Torres Martínez', '71188220', 'M', 999240124, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Diego', 'Díaz', 'Reyes', 'Diego Díaz Reyes', '72241952', 'M', 969861619, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('David', 'Gonzales', 'Rivera', 'David Gonzales Rivera', '74380383', 'M', 968996762, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Oliver', 'Ramírez', 'Salazar', 'Oliver Ramírez Salazar', '72506487', 'M', 961476744, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Marcos', 'Mendoza', 'Medina', 'Marcos Mendoza Medina', '72179343', 'M', 973840151, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Thiago', 'Chávez', 'Aguilar', 'Thiago Chávez Aguilar', '72085270', 'M', 994871071, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Marco', 'Espinoza', 'Morales', 'Marco Espinoza Morales', '74069469', 'M', 985930812, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Álex', 'Castillo', 'Paredes', 'Álex Castillo Paredes', '74895283', 'M', 983229516, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Javier', 'Fernández', 'Quispe', 'Javier Fernández Quispe', '73498638', 'M', 951625955, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Izan', 'Vargas', 'Flores', 'Izan Vargas Flores', '70216182', 'M', 965788004, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Bruno', 'Gutiérrez', 'Sánchez', 'Bruno Gutiérrez Sánchez', '70821662', 'M', 966817402, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Miguel', 'Cruz', 'García', 'Miguel Cruz García', '73403882', 'M', 974669045, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Antonio', 'Ruiz', 'Rodríguez', 'Antonio Ruiz Rodríguez', '74476039', 'M', 957177407, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Gonzalo', 'De la Cruz', 'Huamán', 'Gonzalo De la Cruz Huamán', '74270998', 'M', 974747454, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Liam', 'Romero', 'Rojas', 'Liam Romero Rojas', '71710147', 'M', 982153642, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Gael', 'Gómez', 'Vásquez', 'Gael Gómez Vásquez', '70078784', 'M', 995388347, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Marc', 'Silva', 'Mamani', 'Marc Silva Mamani', '73828837', 'M', 952602457, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Carlos', 'Córdova', 'López', 'Carlos Córdova López', '70749339', 'M', 964697396, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Juan', 'Condori', 'Ramos', 'Juan Condori Ramos', '72678615', 'M', 963552913, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Ángel', 'Catro', 'Pérez', 'Ángel Catro Pérez', '74439433', 'M', 961558886, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Dylan', 'Martínez', 'Torres', 'Dylan Martínez Torres', '72438651', 'M', 983572075, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Nicolás', 'Reyes', 'Díaz', 'Nicolás Reyes Díaz', '71445298', 'M', 999322446, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('José', 'Rivera', 'Gonzales', 'José Rivera Gonzales', '70087370', 'M', 959357247, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Sergio', 'Salazar', 'Ramírez', 'Sergio Salazar Ramírez', '74612493', 'M', 963145935, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Gabriel', 'Medina', 'Mendoza', 'Gabriel Medina Mendoza', '70361398', 'M', 951264898, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Luca', 'Aguilar', 'Chávez', 'Luca Aguilar Chávez', '71999673', 'M', 960119955, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Jorge', 'Morales', 'Espinoza', 'Jorge Morales Espinoza', '70027531', 'M', 970891548, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Darío', 'Paredes', 'Castillo', 'Darío Paredes Castillo', '73063057', 'M', 978854744, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Íker', 'Quispe', 'Fernández', 'Íker Quispe Fernández', '73879504', 'M', 970054936, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Samuel', 'Flores', 'Vargas', 'Samuel Flores Vargas', '71434625', 'M', 996278955, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Eric', 'Sánchez', 'Gutiérrez', 'Eric Sánchez Gutiérrez', '70836449', 'M', 957453296, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Adam', 'García', 'Cruz', 'Adam García Cruz', '72536057', 'M', 955211793, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Héctor', 'Rodríguez', 'Ruiz', 'Héctor Rodríguez Ruiz', '70230602', 'M', 972284959, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Francisco', 'Huamán', 'De la Cruz', 'Francisco Huamán De la Cruz', '73965884', 'M', 958273615, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Rodrigo', 'Rojas', 'Romero', 'Rodrigo Rojas Romero', '72745598', 'M', 969182064, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Jesús', 'Vásquez', 'Gómez', 'Jesús Vásquez Gómez', '74932222', 'M', 970912973, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Erik', 'Mamani', 'Silva', 'Erik Mamani Silva', '70505195', 'M', 978121265, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Amir', 'López', 'Córdova', 'Amir López Córdova', '74139771', 'M', 993310676, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Jaime', 'Ramos', 'Condori', 'Jaime Ramos Condori', '71990022', 'M', 969527928, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Ian', 'Pérez', 'Catro', 'Ian Pérez Catro', '73955097', 'M', 989020964, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Rubén', 'Torres', 'Martínez', 'Rubén Torres Martínez', '70526823', 'M', 996303687, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Aarón', 'Díaz', 'Reyes', 'Aarón Díaz Reyes', '74561906', 'M', 971897668, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Iván', 'Gonzales', 'Rivera', 'Iván Gonzales Rivera', '73417616', 'M', 969099768, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Pau', 'Ramírez', 'Salazar', 'Pau Ramírez Salazar', '70540897', 'M', 965873817, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Víctor', 'Mendoza', 'Medina', 'Víctor Mendoza Medina', '70890137', 'M', 973186860, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Guillermo', 'Chávez', 'Aguilar', 'Guillermo Chávez Aguilar', '72929882', 'M', 999689649, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Luis', 'Espinoza', 'Morales', 'Luis Espinoza Morales', '71379180', 'M', 992654258, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Mohamed', 'Castillo', 'Paredes', 'Mohamed Castillo Paredes', '71392594', 'M', 955372532, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Pedro', 'Fernández', 'Quispe', 'Pedro Fernández Quispe', '73155871', 'M', 965594156, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Julen', 'Vargas', 'Flores', 'Julen Vargas Flores', '73243383', 'M', 965631151, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Unai', 'Gutiérrez', 'Sánchez', 'Unai Gutiérrez Sánchez', '71229420', 'M', 981054731, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Rafael', 'Cruz', 'García', 'Rafael Cruz García', '74734094', 'M', 962777271, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Santiago', 'Ruiz', 'Rodríguez', 'Santiago Ruiz Rodríguez', '70482567', 'M', 953740177, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Saúl', 'De la Cruz', 'Huamán', 'Saúl De la Cruz Huamán', '71443339', 'M', 984427103, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Alberto', 'Romero', 'Rojas', 'Alberto Romero Rojas', '71600048', 'M', 994794633, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Noah', 'Gómez', 'Vásquez', 'Noah Gómez Vásquez', '72479461', 'M', 989762128, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Aitor', 'Silva', 'Mamani', 'Aitor Silva Mamani', '72179809', 'M', 991464839, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Joel', 'Córdova', 'López', 'Joel Córdova López', '73574472', 'M', 984562057, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Nil', 'Condori', 'Ramos', 'Nil Condori Ramos', '74433804', 'M', 998886879, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Jan', 'Catro', 'Pérez', 'Jan Catro Pérez', '72374079', 'M', 993781357, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Pol', 'Martínez', 'Torres', 'Pol Martínez Torres', '72073173', 'M', 964191299, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Raúl', 'Reyes', 'Díaz', 'Raúl Reyes Díaz', '71388500', 'M', 972344255, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Matías', 'Rivera', 'Gonzales', 'Matías Rivera Gonzales', '73483509', 'M', 979485156, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Martí', 'Salazar', 'Ramírez', 'Martí Salazar Ramírez', '72913348', 'M', 964569311, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Fernando', 'Medina', 'Mendoza', 'Fernando Medina Mendoza', '70314897', 'M', 964440908, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Andrés', 'Aguilar', 'Chávez', 'Andrés Aguilar Chávez', '74236980', 'M', 970076933, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Rayan', 'Morales', 'Espinoza', 'Rayan Morales Espinoza', '70338465', 'M', 976206375, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Alonso', 'Paredes', 'Castillo', 'Alonso Paredes Castillo', '70346154', 'M', 956979970, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Ismael', 'Quispe', 'Fernández', 'Ismael Quispe Fernández', '71134387', 'M', 998956876, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Asier', 'Flores', 'Vargas', 'Asier Flores Vargas', '71892396', 'M', 958019767, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Biel', 'Sánchez', 'Gutiérrez', 'Biel Sánchez Gutiérrez', '73433077', 'M', 981029820, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Ander', 'García', 'Cruz', 'Ander García Cruz', '74173119', 'M', 961035387, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Aleix', 'Rodríguez', 'Ruiz', 'Aleix Rodríguez Ruiz', '74238633', 'M', 992327079, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Axel', 'Huamán', 'De la Cruz', 'Axel Huamán De la Cruz', '72760714', 'M', 968645932, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Alan', 'Rojas', 'Romero', 'Alan Rojas Romero', '71373712', 'M', 999423150, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Ignacio', 'Vásquez', 'Gómez', 'Ignacio Vásquez Gómez', '74272798', 'M', 969004994, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Fabio', 'Mamani', 'Silva', 'Fabio Mamani Silva', '72593390', 'M', 960620261, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Neizan', 'López', 'Córdova', 'Neizan López Córdova', '71681142', 'M', 967337876, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Jon', 'Ramos', 'Condori', 'Jon Ramos Condori', '74704652', 'M', 980130024, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Teo', 'Pérez', 'Catro', 'Teo Pérez Catro', '73444487', 'M', 997088116, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Isaac', 'Torres', 'Martínez', 'Isaac Torres Martínez', '70662527', 'M', 986774696, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Arnau', 'Díaz', 'Reyes', 'Arnau Díaz Reyes', '74190293', 'M', 972719657, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Luka', 'Gonzales', 'Rivera', 'Luka Gonzales Rivera', '73696947', 'M', 959827028, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Max', 'Ramírez', 'Salazar', 'Max Ramírez Salazar', '71274056', 'M', 995208030, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Imran', 'Mendoza', 'Medina', 'Imran Mendoza Medina', '70789655', 'M', 957143776, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Youssef', 'Chávez', 'Aguilar', 'Youssef Chávez Aguilar', '71644327', 'M', 993700883, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Anas', 'Espinoza', 'Morales', 'Anas Espinoza Morales', '70604335', 'M', 953816169, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Elías', 'Castillo', 'Paredes', 'Elías Castillo Paredes', '74619865', 'M', 981334584, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Lucía', 'Quispe', 'Fernández', 'Lucía Quispe Fernández', '73681232', 'F', 986866393, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Sofía', 'Flores', 'Vargas', 'Sofía Flores Vargas', '70369641', 'F', 974781361, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Martina', 'Sánchez', 'Gutiérrez', 'Martina Sánchez Gutiérrez', '74698966', 'F', 963945382, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('María', 'García', 'Cruz', 'María García Cruz', '70813189', 'F', 983013473, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Julia', 'Rodríguez', 'Ruiz', 'Julia Rodríguez Ruiz', '71981862', 'F', 958430470, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Paula', 'Huamán', 'De la Cruz', 'Paula Huamán De la Cruz', '70871068', 'F', 992538982, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Valeria', 'Rojas', 'Romero', 'Valeria Rojas Romero', '71148457', 'F', 985347126, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Emma', 'Vásquez', 'Gómez', 'Emma Vásquez Gómez', '72484358', 'F', 975034280, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Daniela', 'Mamani', 'Silva', 'Daniela Mamani Silva', '73115722', 'F', 981613088, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Carla', 'López', 'Córdova', 'Carla López Córdova', '72201955', 'F', 968477129, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Alba', 'Ramos', 'Condori', 'Alba Ramos Condori', '72986518', 'F', 966035141, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Noa', 'Pérez', 'Catro', 'Noa Pérez Catro', '72508071', 'F', 981560850, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Alma', 'Torres', 'Martínez', 'Alma Torres Martínez', '71119435', 'F', 995600397, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Sara', 'Díaz', 'Reyes', 'Sara Díaz Reyes', '70977536', 'F', 973664646, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Carmen', 'Gonzales', 'Rivera', 'Carmen Gonzales Rivera', '71219123', 'F', 967891867, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Vega', 'Ramírez', 'Salazar', 'Vega Ramírez Salazar', '74016718', 'F', 984813881, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Lara', 'Mendoza', 'Medina', 'Lara Mendoza Medina', '71960483', 'F', 992693661, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Mia', 'Chávez', 'Aguilar', 'Mia Chávez Aguilar', '70756019', 'F', 997524532, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Valentina', 'Espinoza', 'Morales', 'Valentina Espinoza Morales', '70268140', 'F', 987147385, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Olivia', 'Castillo', 'Paredes', 'Olivia Castillo Paredes', '74321860', 'F', 953516082, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Claudia', 'Fernández', 'Quispe', 'Claudia Fernández Quispe', '70429929', 'F', 991624425, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Jimena', 'Vargas', 'Flores', 'Jimena Vargas Flores', '71235133', 'F', 953409536, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Lola', 'Gutiérrez', 'Sánchez', 'Lola Gutiérrez Sánchez', '70654593', 'F', 990910038, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Chlóe', 'Cruz', 'García', 'Chlóe Cruz García', '74894660', 'F', 962663734, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Aitana', 'Ruiz', 'Rodríguez', 'Aitana Ruiz Rodríguez', '73898109', 'F', 964429624, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Abril', 'De la Cruz', 'Huamán', 'Abril De la Cruz Huamán', '74403312', 'F', 989921320, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Ana', 'Romero', 'Rojas', 'Ana Romero Rojas', '70331752', 'F', 994669926, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Laia', 'Gómez', 'Vásquez', 'Laia Gómez Vásquez', '73457077', 'F', 991854565, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Triana', 'Silva', 'Mamani', 'Triana Silva Mamani', '73321264', 'F', 959659558, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Candela', 'Córdova', 'López', 'Candela Córdova López', '71743591', 'F', 995364016, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Alejandra', 'Condori', 'Ramos', 'Alejandra Condori Ramos', '71410175', 'F', 964725233, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Elena', 'Catro', 'Pérez', 'Elena Catro Pérez', '71706272', 'F', 979661045, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Vera', 'Martínez', 'Torres', 'Vera Martínez Torres', '73761234', 'F', 959111032, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Manuela', 'Reyes', 'Díaz', 'Manuela Reyes Díaz', '74925698', 'F', 978739055, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Adriana', 'Rivera', 'Gonzales', 'Adriana Rivera Gonzales', '71323743', 'F', 980101353, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Inés', 'Salazar', 'Ramírez', 'Inés Salazar Ramírez', '73902952', 'F', 994928585, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Marta', 'Medina', 'Mendoza', 'Marta Medina Mendoza', '70038875', 'F', 985532829, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Carlota', 'Aguilar', 'Chávez', 'Carlota Aguilar Chávez', '70276711', 'F', 971620702, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Irene', 'Morales', 'Espinoza', 'Irene Morales Espinoza', '71306393', 'F', 951749925, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Victoria', 'Paredes', 'Castillo', 'Victoria Paredes Castillo', '73191213', 'F', 993774215, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Blanca', 'Quispe', 'Fernández', 'Blanca Quispe Fernández', '74722317', 'F', 951428872, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Marina', 'Flores', 'Vargas', 'Marina Flores Vargas', '70258467', 'F', 988461610, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Laura', 'Sánchez', 'Gutiérrez', 'Laura Sánchez Gutiérrez', '74138119', 'F', 960326570, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Rocío', 'García', 'Cruz', 'Rocío García Cruz', '70592775', 'F', 973629337, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Alicia', 'Rodríguez', 'Ruiz', 'Alicia Rodríguez Ruiz', '74896767', 'F', 979174864, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Clara', 'Huamán', 'De la Cruz', 'Clara Huamán De la Cruz', '70366421', 'F', 980586301, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Nora', 'Rojas', 'Romero', 'Nora Rojas Romero', '73110966', 'F', 976982036, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Lía', 'Vásquez', 'Gómez', 'Lía Vásquez Gómez', '74824965', 'F', 960788459, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Ariadna', 'Mamani', 'Silva', 'Ariadna Mamani Silva', '70854679', 'F', 976212483, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Zoe', 'López', 'Córdova', 'Zoe López Córdova', '74599025', 'F', 999388850, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Amira', 'Ramos', 'Condori', 'Amira Ramos Condori', '72797807', 'F', 972167621, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Gala', 'Pérez', 'Catro', 'Gala Pérez Catro', '74381314', 'F', 983670897, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Celia', 'Torres', 'Martínez', 'Celia Torres Martínez', '72438877', 'F', 972430357, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Leire', 'Díaz', 'Reyes', 'Leire Díaz Reyes', '73842065', 'F', 975199417, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Eva', 'Gonzales', 'Rivera', 'Eva Gonzales Rivera', '73588149', 'F', 957389736, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Ángela', 'Ramírez', 'Salazar', 'Ángela Ramírez Salazar', '72690263', 'F', 988642334, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Andrea', 'Mendoza', 'Medina', 'Andrea Mendoza Medina', '74384602', 'F', 962679810, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('África', 'Chávez', 'Aguilar', 'África Chávez Aguilar', '74913023', 'F', 954162066, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Luna', 'Espinoza', 'Morales', 'Luna Espinoza Morales', '74265813', 'F', 968876670, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Ainhoa', 'Castillo', 'Paredes', 'Ainhoa Castillo Paredes', '73529763', 'F', 985508423, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Ainara', 'Fernández', 'Quispe', 'Ainara Fernández Quispe', '71088270', 'F', 970140447, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('India', 'Vargas', 'Flores', 'India Vargas Flores', '73409301', 'F', 983643910, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Nerea', 'Gutiérrez', 'Sánchez', 'Nerea Gutiérrez Sánchez', '74166758', 'F', 990771057, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Ona', 'Cruz', 'García', 'Ona Cruz García', '72827646', 'F', 974685691, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Elsa', 'Ruiz', 'Rodríguez', 'Elsa Ruiz Rodríguez', '71904760', 'F', 987750244, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Isabel', 'De la Cruz', 'Huamán', 'Isabel De la Cruz Huamán', '70183979', 'F', 951128048, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Leyre', 'Romero', 'Rojas', 'Leyre Romero Rojas', '74200721', 'F', 967289368, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Gabriela', 'Gómez', 'Vásquez', 'Gabriela Gómez Vásquez', '73115577', 'F', 955193912, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Aina', 'Silva', 'Mamani', 'Aina Silva Mamani', '71322937', 'F', 995474299, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Cayetana', 'Córdova', 'López', 'Cayetana Córdova López', '71409976', 'F', 991019756, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Iria', 'Condori', 'Ramos', 'Iria Condori Ramos', '72865622', 'F', 968210716, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Jana', 'Catro', 'Pérez', 'Jana Catro Pérez', '74618350', 'F', 977977785, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Mar', 'Martínez', 'Torres', 'Mar Martínez Torres', '72389949', 'F', 976238941, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Cloe', 'Reyes', 'Díaz', 'Cloe Reyes Díaz', '71131779', 'F', 983682377, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Lina', 'Rivera', 'Gonzales', 'Lina Rivera Gonzales', '71940487', 'F', 953833504, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Julieta', 'Salazar', 'Ramírez', 'Julieta Salazar Ramírez', '71985335', 'F', 990523504, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Adara', 'Medina', 'Mendoza', 'Adara Medina Mendoza', '70679874', 'F', 983166473, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Naia', 'Aguilar', 'Chávez', 'Naia Aguilar Chávez', '70073195', 'F', 963214195, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Iris', 'Morales', 'Espinoza', 'Iris Morales Espinoza', '72303634', 'F', 956461889, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Nour', 'Paredes', 'Castillo', 'Nour Paredes Castillo', '72067626', 'F', 984747345, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Mara', 'Quispe', 'Fernández', 'Mara Quispe Fernández', '72321616', 'F', 992734213, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Helena', 'Flores', 'Vargas', 'Helena Flores Vargas', '72849582', 'F', 972327138, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Yasmín', 'Sánchez', 'Gutiérrez', 'Yasmín Sánchez Gutiérrez', '70518706', 'F', 993101884, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Natalia', 'García', 'Cruz', 'Natalia García Cruz', '70887583', 'F', 981236247, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Arlet', 'Rodríguez', 'Ruiz', 'Arlet Rodríguez Ruiz', '74442891', 'F', 993213794, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Diana', 'Huamán', 'De la Cruz', 'Diana Huamán De la Cruz', '70948117', 'F', 978614517, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Aroa', 'Rojas', 'Romero', 'Aroa Rojas Romero', '74592172', 'F', 984502890, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Amaia', 'Vásquez', 'Gómez', 'Amaia Vásquez Gómez', '71541133', 'F', 956840904, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Cristina', 'Mamani', 'Silva', 'Cristina Mamani Silva', '71203957', 'F', 978468856, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Nahia', 'López', 'Córdova', 'Nahia López Córdova', '71628228', 'F', 986611925, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Isabella', 'Ramos', 'Condori', 'Isabella Ramos Condori', '74351622', 'F', 995910457, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Malak', 'Pérez', 'Catro', 'Malak Pérez Catro', '73727564', 'F', 979917226, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Elia', 'Torres', 'Martínez', 'Elia Torres Martínez', '71379879', 'F', 966389552, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Carolina', 'Díaz', 'Reyes', 'Carolina Díaz Reyes', '70678379', 'F', 992821069, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Berta', 'Gonzales', 'Rivera', 'Berta Gonzales Rivera', '74119487', 'F', 985887086, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Fátima', 'Ramírez', 'Salazar', 'Fátima Ramírez Salazar', '73537511', 'F', 950931969, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Nuria', 'Mendoza', 'Medina', 'Nuria Mendoza Medina', '72248914', 'F', 969798895, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Azahara', 'Chávez', 'Aguilar', 'Azahara Chávez Aguilar', '72379816', 'F', 974400422, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Macarena', 'Espinoza', 'Morales', 'Macarena Espinoza Morales', '74486701', 'F', 979660660, CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_USUARIOS (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE_COMPLETO, DNI, SEXO, TELEFONO,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('Aurora', 'Castillo', 'Paredes', 'Aurora Castillo Paredes', '72177398', 'F', 954300186, CURRENT_DATE, 1);

--DELETE FROM SCHEMA_TIENDA.TBL_CUENTAS;
INSERT INTO SCHEMA_TIENDA.TBL_CUENTAS (ID_USUARIO,CUENTA,CONTRASEÑA,TIPO_CUENTA,FLAG_ACTIVIDAD,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('1', 'DDELACRUZT', '722987', '1', '1', CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_CUENTAS (ID_USUARIO,CUENTA,CONTRASEÑA,TIPO_CUENTA,FLAG_ACTIVIDAD,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('2', 'HQUISPEF', '708979', '2', '1', CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_CUENTAS (ID_USUARIO,CUENTA,CONTRASEÑA,TIPO_CUENTA,FLAG_ACTIVIDAD,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('3', 'MFLORESV', '708979', '2', '1', CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_CUENTAS (ID_USUARIO,CUENTA,CONTRASEÑA,TIPO_CUENTA,FLAG_ACTIVIDAD,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('4', 'MSANCHEZG', '725976', '2', '1', CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_CUENTAS (ID_USUARIO,CUENTA,CONTRASEÑA,TIPO_CUENTA,FLAG_ACTIVIDAD,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('5', 'LGARCIAC', '729984', '2', '1', CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_CUENTAS (ID_USUARIO,CUENTA,CONTRASEÑA,TIPO_CUENTA,FLAG_ACTIVIDAD,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('6', 'LRODRIGUEZR', '732980', '2', '1', CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_CUENTAS (ID_USUARIO,CUENTA,CONTRASEÑA,TIPO_CUENTA,FLAG_ACTIVIDAD,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('7', 'DHUAMAND', '729986', '2', '1', CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_CUENTAS (ID_USUARIO,CUENTA,CONTRASEÑA,TIPO_CUENTA,FLAG_ACTIVIDAD,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('8', 'AROJASR', '710991', '2', '1', CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_CUENTAS (ID_USUARIO,CUENTA,CONTRASEÑA,TIPO_CUENTA,FLAG_ACTIVIDAD,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('9', 'MVASQUEZG', '704961', '2', '1', CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_CUENTAS (ID_USUARIO,CUENTA,CONTRASEÑA,TIPO_CUENTA,FLAG_ACTIVIDAD,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('10', 'PMAMANIS', '745950', '2', '1', CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_CUENTAS (ID_USUARIO,CUENTA,CONTRASEÑA,TIPO_CUENTA,FLAG_ACTIVIDAD,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('45', 'AGARCIAC', '730950', '2', '1', CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_CUENTAS (ID_USUARIO,CUENTA,CONTRASEÑA,TIPO_CUENTA,FLAG_ACTIVIDAD,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('46', 'HRODRIGUEZR', '729964', '2', '1', CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_CUENTAS (ID_USUARIO,CUENTA,CONTRASEÑA,TIPO_CUENTA,FLAG_ACTIVIDAD,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('47', 'FHUAMAND', '734983', '2', '1', CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_CUENTAS (ID_USUARIO,CUENTA,CONTRASEÑA,TIPO_CUENTA,FLAG_ACTIVIDAD,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('48', 'RROJASR', '743995', '2', '1', CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_CUENTAS (ID_USUARIO,CUENTA,CONTRASEÑA,TIPO_CUENTA,FLAG_ACTIVIDAD,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('49', 'JVASQUEZG', '706967', '2', '1', CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_CUENTAS (ID_USUARIO,CUENTA,CONTRASEÑA,TIPO_CUENTA,FLAG_ACTIVIDAD,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('50', 'EMAMANIS', '722950', '2', '1', CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_CUENTAS (ID_USUARIO,CUENTA,CONTRASEÑA,TIPO_CUENTA,FLAG_ACTIVIDAD,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('51', 'ALOPEZC', '739956', '2', '1', CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_CUENTAS (ID_USUARIO,CUENTA,CONTRASEÑA,TIPO_CUENTA,FLAG_ACTIVIDAD,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('52', 'JRAMOSC', '703986', '2', '1', CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_CUENTAS (ID_USUARIO,CUENTA,CONTRASEÑA,TIPO_CUENTA,FLAG_ACTIVIDAD,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('53', 'IPEREZC', '733991', '2', '1', CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_CUENTAS (ID_USUARIO,CUENTA,CONTRASEÑA,TIPO_CUENTA,FLAG_ACTIVIDAD,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('54', 'RTORRESM', '704996', '2', '1', CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_CUENTAS (ID_USUARIO,CUENTA,CONTRASEÑA,TIPO_CUENTA,FLAG_ACTIVIDAD,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('55', 'ADIAZR', '718976', '2', '1', CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_CUENTAS (ID_USUARIO,CUENTA,CONTRASEÑA,TIPO_CUENTA,FLAG_ACTIVIDAD,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('56', 'IGONZALESR', '715975', '2', '1', CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_CUENTAS (ID_USUARIO,CUENTA,CONTRASEÑA,TIPO_CUENTA,FLAG_ACTIVIDAD,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('57', 'PRAMIREZS', '701957', '2', '1', CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_CUENTAS (ID_USUARIO,CUENTA,CONTRASEÑA,TIPO_CUENTA,FLAG_ACTIVIDAD,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('58', 'VMENDOZAM', '735988', '2', '1', CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_CUENTAS (ID_USUARIO,CUENTA,CONTRASEÑA,TIPO_CUENTA,FLAG_ACTIVIDAD,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('59', 'GCHAVEZA', '715977', '2', '1', CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_CUENTAS (ID_USUARIO,CUENTA,CONTRASEÑA,TIPO_CUENTA,FLAG_ACTIVIDAD,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('60', 'LESPINOZAM', '726956', '2', '1', CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_CUENTAS (ID_USUARIO,CUENTA,CONTRASEÑA,TIPO_CUENTA,FLAG_ACTIVIDAD,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('61', 'MCASTILLOP', '719957', '2', '1', CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_CUENTAS (ID_USUARIO,CUENTA,CONTRASEÑA,TIPO_CUENTA,FLAG_ACTIVIDAD,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('62', 'PFERNANDEZQ', '732959', '2', '1', CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_CUENTAS (ID_USUARIO,CUENTA,CONTRASEÑA,TIPO_CUENTA,FLAG_ACTIVIDAD,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('63', 'JVARGASF', '749966', '2', '1', CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_CUENTAS (ID_USUARIO,CUENTA,CONTRASEÑA,TIPO_CUENTA,FLAG_ACTIVIDAD,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('64', 'UGUTIERREZS', '713958', '2', '1', CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_CUENTAS (ID_USUARIO,CUENTA,CONTRASEÑA,TIPO_CUENTA,FLAG_ACTIVIDAD,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('65', 'RCRUZG', '740998', '2', '1', CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_CUENTAS (ID_USUARIO,CUENTA,CONTRASEÑA,TIPO_CUENTA,FLAG_ACTIVIDAD,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('66', 'SRUIZR', '731984', '2', '1', CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_CUENTAS (ID_USUARIO,CUENTA,CONTRASEÑA,TIPO_CUENTA,FLAG_ACTIVIDAD,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('67', 'SDELACRUZH', '724956', '2', '1', CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_CUENTAS (ID_USUARIO,CUENTA,CONTRASEÑA,TIPO_CUENTA,FLAG_ACTIVIDAD,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('68', 'AROMEROR', '739990', '2', '1', CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_CUENTAS (ID_USUARIO,CUENTA,CONTRASEÑA,TIPO_CUENTA,FLAG_ACTIVIDAD,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('69', 'NGOMEZV', '742979', '2', '1', CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_CUENTAS (ID_USUARIO,CUENTA,CONTRASEÑA,TIPO_CUENTA,FLAG_ACTIVIDAD,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('70', 'ASILVAM', '713988', '2', '1', CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_CUENTAS (ID_USUARIO,CUENTA,CONTRASEÑA,TIPO_CUENTA,FLAG_ACTIVIDAD,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('71', 'JCORDOVAL', '719986', '2', '1', CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_CUENTAS (ID_USUARIO,CUENTA,CONTRASEÑA,TIPO_CUENTA,FLAG_ACTIVIDAD,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('72', 'NCONDORIR', '702950', '2', '1', CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_CUENTAS (ID_USUARIO,CUENTA,CONTRASEÑA,TIPO_CUENTA,FLAG_ACTIVIDAD,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('73', 'JCATROP', '725999', '2', '1', CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_CUENTAS (ID_USUARIO,CUENTA,CONTRASEÑA,TIPO_CUENTA,FLAG_ACTIVIDAD,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('74', 'PMARTINEZT', '739984', '2', '1', CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_CUENTAS (ID_USUARIO,CUENTA,CONTRASEÑA,TIPO_CUENTA,FLAG_ACTIVIDAD,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('75', 'RREYESD', '700953', '2', '1', CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_CUENTAS (ID_USUARIO,CUENTA,CONTRASEÑA,TIPO_CUENTA,FLAG_ACTIVIDAD,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('76', 'MRIVERAG', '704985', '2', '1', CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_CUENTAS (ID_USUARIO,CUENTA,CONTRASEÑA,TIPO_CUENTA,FLAG_ACTIVIDAD,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('77', 'MSALAZARR', '738953', '2', '1', CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_CUENTAS (ID_USUARIO,CUENTA,CONTRASEÑA,TIPO_CUENTA,FLAG_ACTIVIDAD,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('78', 'FMEDINAM', '725975', '2', '1', CURRENT_DATE, 1);
INSERT INTO SCHEMA_TIENDA.TBL_CUENTAS (ID_USUARIO,CUENTA,CONTRASEÑA,TIPO_CUENTA,FLAG_ACTIVIDAD,FECHA_REGISTRO,USUARIO_REGISTRO)  VALUES('79', 'AAGUILARC', '709985', '2', '1', CURRENT_DATE, 1);



-- DELETE FROM SCHEMA_TIENDA.TBL_PROVEEDORES
INSERT INTO SCHEMA_TIENDA.TBL_PROVEEDORES (ID_PROVEEDOR, NOMBRE, DIRECCION, TELEFONO, CORREO)
VALUES
    (DEFAULT, 'Proveedor1', 'Calle 123, Ciudad A', 912345678, 'proveedor1@email.com'),
    (DEFAULT, 'Proveedor2', 'Avenida XYZ, Ciudad B', 998765432, 'proveedor2@email.com'),
    (DEFAULT, 'Proveedor3', 'Calle ABC, Ciudad C', 955544433, 'proveedor3@email.com'),
    (DEFAULT, 'Proveedor4', 'Avenida 456, Ciudad D', 911122334, 'proveedor4@email.com'),
    (DEFAULT, 'Proveedor5', 'Calle ZZZ, Ciudad E', 988877766, 'proveedor5@email.com'),
    (DEFAULT, 'Proveedor6', 'Avenida KLM, Ciudad F', 933322211, 'proveedor6@email.com'),
    (DEFAULT, 'Proveedor7', 'Calle 789, Ciudad G', 944455566, 'proveedor7@email.com'),
    (DEFAULT, 'Proveedor8', 'Avenida HIJ, Ciudad H', 999888777, 'proveedor8@email.com'),
    (DEFAULT, 'Proveedor9', 'Calle LMN, Ciudad I', 966677788, 'proveedor9@email.com'),
    (DEFAULT, 'Proveedor10', 'Avenida UVW, Ciudad J', 912312312, 'proveedor10@email.com'),
    (DEFAULT, 'Proveedor11', 'Calle 456, Ciudad K', 945678901, 'proveedor11@email.com'),
    (DEFAULT, 'Proveedor12', 'Avenida QWE, Ciudad L', 978901234, 'proveedor12@email.com'),
    (DEFAULT, 'Proveedor13', 'Calle ASD, Ciudad M', 934567890, 'proveedor13@email.com'),
    (DEFAULT, 'Proveedor14', 'Avenida YUI, Ciudad N', 967890123, 'proveedor14@email.com'),
    (DEFAULT, 'Proveedor15', 'Calle OPU, Ciudad O', 923456789, 'proveedor15@email.com'),
    (DEFAULT, 'Proveedor16', 'Avenida MNB, Ciudad P', 987654321, 'proveedor16@email.com'),
    (DEFAULT, 'Proveedor17', 'Calle XYZ, Ciudad Q', 911100999, 'proveedor17@email.com'),
    (DEFAULT, 'Proveedor18', 'Avenida PLQ, Ciudad R', 999000111, 'proveedor18@email.com'),
    (DEFAULT, 'Proveedor19', 'Calle 321, Ciudad S', 944433322, 'proveedor19@email.com'),
    (DEFAULT, 'Proveedor20', 'Avenida JKL, Ciudad T', 955566677, 'proveedor20@email.com');

-- DELETE FROM SCHEMA_TIENDA.TBL_COLABORADORES
INSERT INTO SCHEMA_TIENDA.TBL_COLABORADORES (ID_USUARIO,ID_CARGO,ID_TURNO,FECHA_INGRESO,FLAG_IS_SUPERVISOR)VALUES(45, 1, 1, '2017-06-01 00:00:00.0',1);
INSERT INTO SCHEMA_TIENDA.TBL_COLABORADORES (ID_USUARIO,ID_CARGO,ID_TURNO,FECHA_INGRESO,FLAG_IS_SUPERVISOR)VALUES(46, 1, 1, '2017-08-01 00:00:00.0',1);
INSERT INTO SCHEMA_TIENDA.TBL_COLABORADORES (ID_USUARIO,ID_CARGO,ID_TURNO,FECHA_INGRESO,FLAG_IS_SUPERVISOR)VALUES(47, 2, 1, '2017-09-01 00:00:00.0',0);
INSERT INTO SCHEMA_TIENDA.TBL_COLABORADORES (ID_USUARIO,ID_CARGO,ID_TURNO,FECHA_INGRESO,FLAG_IS_SUPERVISOR)VALUES(48, 2, 1, '2017-10-01 00:00:00.0',0);
INSERT INTO SCHEMA_TIENDA.TBL_COLABORADORES (ID_USUARIO,ID_CARGO,ID_TURNO,FECHA_INGRESO,FLAG_IS_SUPERVISOR)VALUES(49, 2, 1, '2017-12-01 00:00:00.0',0);
INSERT INTO SCHEMA_TIENDA.TBL_COLABORADORES (ID_USUARIO,ID_CARGO,ID_TURNO,FECHA_INGRESO,FLAG_IS_SUPERVISOR)VALUES(50, 2, 1, '2018-01-01 00:00:00.0',0);
INSERT INTO SCHEMA_TIENDA.TBL_COLABORADORES (ID_USUARIO,ID_CARGO,ID_TURNO,FECHA_INGRESO,FLAG_IS_SUPERVISOR)VALUES(51, 2, 1, '2018-02-01 00:00:00.0',0);
INSERT INTO SCHEMA_TIENDA.TBL_COLABORADORES (ID_USUARIO,ID_CARGO,ID_TURNO,FECHA_INGRESO,FLAG_IS_SUPERVISOR)VALUES(52, 2, 1, '2018-03-01 00:00:00.0',0);
INSERT INTO SCHEMA_TIENDA.TBL_COLABORADORES (ID_USUARIO,ID_CARGO,ID_TURNO,FECHA_INGRESO,FLAG_IS_SUPERVISOR)VALUES(53, 3, 1, '2018-04-01 00:00:00.0',0);
INSERT INTO SCHEMA_TIENDA.TBL_COLABORADORES (ID_USUARIO,ID_CARGO,ID_TURNO,FECHA_INGRESO,FLAG_IS_SUPERVISOR)VALUES(54, 3, 1, '2018-05-01 00:00:00.0',0);
INSERT INTO SCHEMA_TIENDA.TBL_COLABORADORES (ID_USUARIO,ID_CARGO,ID_TURNO,FECHA_INGRESO,FLAG_IS_SUPERVISOR)VALUES(55, 3, 1, '2018-06-01 00:00:00.0',0);
INSERT INTO SCHEMA_TIENDA.TBL_COLABORADORES (ID_USUARIO,ID_CARGO,ID_TURNO,FECHA_INGRESO,FLAG_IS_SUPERVISOR)VALUES(56, 3, 1, '2018-07-01 00:00:00.0',0);
INSERT INTO SCHEMA_TIENDA.TBL_COLABORADORES (ID_USUARIO,ID_CARGO,ID_TURNO,FECHA_INGRESO,FLAG_IS_SUPERVISOR)VALUES(57, 3, 1, '2018-08-01 00:00:00.0',0);
INSERT INTO SCHEMA_TIENDA.TBL_COLABORADORES (ID_USUARIO,ID_CARGO,ID_TURNO,FECHA_INGRESO,FLAG_IS_SUPERVISOR)VALUES(58, 4, 1, '2018-09-01 00:00:00.0',0);
INSERT INTO SCHEMA_TIENDA.TBL_COLABORADORES (ID_USUARIO,ID_CARGO,ID_TURNO,FECHA_INGRESO,FLAG_IS_SUPERVISOR)VALUES(59, 4, 2, '2018-10-01 00:00:00.0',0);
INSERT INTO SCHEMA_TIENDA.TBL_COLABORADORES (ID_USUARIO,ID_CARGO,ID_TURNO,FECHA_INGRESO,FLAG_IS_SUPERVISOR)VALUES(60, 4, 2, '2018-12-01 00:00:00.0',0);
INSERT INTO SCHEMA_TIENDA.TBL_COLABORADORES (ID_USUARIO,ID_CARGO,ID_TURNO,FECHA_INGRESO,FLAG_IS_SUPERVISOR)VALUES(61, 5, 2, '2018-12-31 23:59:59.0',1);
INSERT INTO SCHEMA_TIENDA.TBL_COLABORADORES (ID_USUARIO,ID_CARGO,ID_TURNO,FECHA_INGRESO,FLAG_IS_SUPERVISOR)VALUES(62, 5, 2, '2019-01-01 00:00:00.0',0);
INSERT INTO SCHEMA_TIENDA.TBL_COLABORADORES (ID_USUARIO,ID_CARGO,ID_TURNO,FECHA_INGRESO,FLAG_IS_SUPERVISOR)VALUES(63, 6, 2, '2019-02-01 00:00:00.0',0);
INSERT INTO SCHEMA_TIENDA.TBL_COLABORADORES (ID_USUARIO,ID_CARGO,ID_TURNO,FECHA_INGRESO,FLAG_IS_SUPERVISOR)VALUES(64, 6, 2, '2019-03-01 00:00:00.0',0);
INSERT INTO SCHEMA_TIENDA.TBL_COLABORADORES (ID_USUARIO,ID_CARGO,ID_TURNO,FECHA_INGRESO,FLAG_IS_SUPERVISOR)VALUES(65, 6, 2, '2019-04-01 00:00:00.0',0);
INSERT INTO SCHEMA_TIENDA.TBL_COLABORADORES (ID_USUARIO,ID_CARGO,ID_TURNO,FECHA_INGRESO,FLAG_IS_SUPERVISOR)VALUES(66, 6, 2, '2019-05-01 00:00:00.0',0);
INSERT INTO SCHEMA_TIENDA.TBL_COLABORADORES (ID_USUARIO,ID_CARGO,ID_TURNO,FECHA_INGRESO,FLAG_IS_SUPERVISOR)VALUES(67, 6, 2, '2019-06-01 00:00:00.0',0);
INSERT INTO SCHEMA_TIENDA.TBL_COLABORADORES (ID_USUARIO,ID_CARGO,ID_TURNO,FECHA_INGRESO,FLAG_IS_SUPERVISOR)VALUES(68, 6, 2, '2019-07-01 00:00:00.0',0);
INSERT INTO SCHEMA_TIENDA.TBL_COLABORADORES (ID_USUARIO,ID_CARGO,ID_TURNO,FECHA_INGRESO,FLAG_IS_SUPERVISOR)VALUES(69, 7, 2, '2019-08-01 00:00:00.0',0);
INSERT INTO SCHEMA_TIENDA.TBL_COLABORADORES (ID_USUARIO,ID_CARGO,ID_TURNO,FECHA_INGRESO,FLAG_IS_SUPERVISOR)VALUES(70, 7, 2, '2019-09-01 00:00:00.0',0);
INSERT INTO SCHEMA_TIENDA.TBL_COLABORADORES (ID_USUARIO,ID_CARGO,ID_TURNO,FECHA_INGRESO,FLAG_IS_SUPERVISOR)VALUES(71, 7, 2, '2019-10-01 00:00:00.0',0);
INSERT INTO SCHEMA_TIENDA.TBL_COLABORADORES (ID_USUARIO,ID_CARGO,ID_TURNO,FECHA_INGRESO,FLAG_IS_SUPERVISOR)VALUES(72, 7, 3, '2019-11-01 00:00:00.0',0);
INSERT INTO SCHEMA_TIENDA.TBL_COLABORADORES (ID_USUARIO,ID_CARGO,ID_TURNO,FECHA_INGRESO,FLAG_IS_SUPERVISOR)VALUES(73, 7, 3, '2019-12-31 23:59:59.0',0);
INSERT INTO SCHEMA_TIENDA.TBL_COLABORADORES (ID_USUARIO,ID_CARGO,ID_TURNO,FECHA_INGRESO,FLAG_IS_SUPERVISOR)VALUES(74, 8, 3, '2020-01-01 00:00:00.0',0);
INSERT INTO SCHEMA_TIENDA.TBL_COLABORADORES (ID_USUARIO,ID_CARGO,ID_TURNO,FECHA_INGRESO,FLAG_IS_SUPERVISOR)VALUES(75, 8, 3, '2020-02-29 23:59:59.0',0);
INSERT INTO SCHEMA_TIENDA.TBL_COLABORADORES (ID_USUARIO,ID_CARGO,ID_TURNO,FECHA_INGRESO,FLAG_IS_SUPERVISOR)VALUES(76, 8, 3, '2020-03-01 00:00:00.0',0);
INSERT INTO SCHEMA_TIENDA.TBL_COLABORADORES (ID_USUARIO,ID_CARGO,ID_TURNO,FECHA_INGRESO,FLAG_IS_SUPERVISOR)VALUES(77, 8, 3, '2020-04-01 00:00:00.0',0);
INSERT INTO SCHEMA_TIENDA.TBL_COLABORADORES (ID_USUARIO,ID_CARGO,ID_TURNO,FECHA_INGRESO,FLAG_IS_SUPERVISOR)VALUES(78, 8, 3, '2020-05-01 00:00:00.0',0);
INSERT INTO SCHEMA_TIENDA.TBL_COLABORADORES (ID_USUARIO,ID_CARGO,ID_TURNO,FECHA_INGRESO,FLAG_IS_SUPERVISOR)VALUES(79, 8, 3, '2020-06-01 00:00:00.0',0);

